version: '3.4'

volumes:
  nestjs_db_data:
    name: nestjs_db_data
services:
  postgres:
    container_name: postgres
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: nestjs
      POSTGRES_USER: nestjs
      POSTGRES_PASSWORD: nestjs
    volumes:
      - nestjs_db_data:/var/lib/postgresql/data

#HOW TO RUN: docker-compose up --build -d
