version: '3.4'

volumes:
  nestjs_db_data:
    name: nestjs_db_data
services:
  postgres:
    container_name: postgres
    image: postgres:15.1
    ports:
      - "5432:5432"
    env_file:
      - ./docker/postgres.env
    volumes:
      - nestjs_db_data:/var/lib/postgresql/data

#HOW TO RUN: docker-compose up --build -d
